AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: [ "lambda.handler" ]
      Role: arn:aws:iam::415740581749:role/lambda-execution-role
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
